import { Player } from './types';

export const POSITIONS = ["PG", "SG", "SF", "PF", "C"];

const toSlug = (name: string) => name.toLowerCase().replace(/'/g, '').replace(/ /g, '-');

export const players: { [key: string]: Player } = {
    // GOAT Tier
    "lebron_james": { name: "LeBron James", pos: "SF", tier: "GOAT", attributes: { inside_scoring: 98, mid_range: 85, three_point: 82, playmaking: 99, perimeter_defense: 90, interior_defense: 80, rebounding: 85, athleticism: 97, basketball_iq: 100 }, career_stats: { usg_pct: 31.5, fg_pct: 50.5 }, shot_tendencies: { inside: 55, mid: 20, three: 25 }, target_minutes: 38, traits: ["Floor General", "Transition Threat", "Alpha Dog"], foul_tendency: 3, img_url: `https://www.statmuse.com/img/nba/players/${toSlug("LeBron James")}.png`, era: "Hyper-Modern Era (2010s-2020s)" },
    "michael_jordan": { name: "Michael Jordan", pos: "SG", tier: "GOAT", attributes: { inside_scoring: 98, mid_range: 100, three_point: 75, playmaking: 90, perimeter_defense: 98, interior_defense: 70, rebounding: 75, athleticism: 98, basketball_iq: 97 }, career_stats: { usg_pct: 33.3, fg_pct: 49.7 }, shot_tendencies: { inside: 45, mid: 50, three: 5 }, target_minutes: 38, traits: ["Clutch Performer", "Alpha Dog", "Unstoppable Scorer"], foul_tendency: 4, img_url: `https://www.statmuse.com/img/nba/players/${toSlug("Michael Jordan")}.png`, era: "Modern Era (1990s-2000s)" },
    "kareem_abdul_jabbar": { name: "Kareem Abdul-Jabbar", pos: "C", tier: "GOAT", attributes: { inside_scoring: 100, mid_range: 88, three_point: 10, playmaking: 78, perimeter_defense: 60, interior_defense: 96, rebounding: 94, athleticism: 88, basketball_iq: 98 }, career_stats: { usg_pct: 28.5, fg_pct: 55.9 }, shot_tendencies: { inside: 80, mid: 20, three: 0 }, target_minutes: 38, traits: ["Unstoppable Scorer", "Rim Protector"], foul_tendency: 6, img_url: `https://www.statmuse.com/img/nba/players/${toSlug("Kareem Abdul-Jabbar")}.png`, era: "Showtime & Three-Point Era (1970s-1980s)" },
    "magic_johnson": { name: "Magic Johnson", pos: "PG", tier: "GOAT", attributes: { inside_scoring: 92, mid_range: 80, three_point: 70, playmaking: 100, perimeter_defense: 80, interior_defense: 60, rebounding: 80, athleticism: 88, basketball_iq: 99 }, career_stats: { usg_pct: 22.8, fg_pct: 52.0 }, shot_tendencies: { inside: 60, mid: 30, three: 10 }, target_minutes: 37, traits: ["Floor General", "Transition Threat"], foul_tendency: 4, img_url: `https://www.statmuse.com/img/nba/players/${toSlug("Magic Johnson")}.png`, era: "Showtime & Three-Point Era (1970s-1980s)" },
    "larry_bird": { name: "Larry Bird", pos: "SF", tier: "GOAT", attributes: { inside_scoring: 88, mid_range: 96, three_point: 90, playmaking: 94, perimeter_defense: 80, interior_defense: 72, rebounding: 88, athleticism: 80, basketball_iq: 100 }, career_stats: { usg_pct: 26.5, fg_pct: 49.6 }, shot_tendencies: { inside: 35, mid: 45, three: 20 }, target_minutes: 38, traits: ["Clutch Performer", "Floor General"], foul_tendency: 5, img_url: `https://www.statmuse.com/img/nba/players/${toSlug("Larry Bird")}.png`, era: "Showtime & Three-Point Era (1970s-1980s)" },
    "wilt_chamberlain": { name: "Wilt Chamberlain", pos: "C", tier: "GOAT", attributes: { inside_scoring: 100, mid_range: 75, three_point: 5, playmaking: 70, perimeter_defense: 50, interior_defense: 95, rebounding: 100, athleticism: 100, basketball_iq: 85 }, career_stats: { usg_pct: 30.0, fg_pct: 54.0 }, shot_tendencies: { inside: 90, mid: 10, three: 0 }, target_minutes: 40, traits: ["Post Anchor", "Tireless Motor"], foul_tendency: 5, img_url: `https://www.statmuse.com/img/nba/players/${toSlug("Wilt Chamberlain")}.png`, era: "Pioneers Era (1940s-1960s)" },
    "bill_russell": { name: "Bill Russell", pos: "C", tier: "GOAT", attributes: { inside_scoring: 75, mid_range: 50, three_point: 5, playmaking: 75, perimeter_defense: 70, interior_defense: 100, rebounding: 99, athleticism: 90, basketball_iq: 100 }, career_stats: { usg_pct: 16.6, fg_pct: 44.0 }, shot_tendencies: { inside: 95, mid: 5, three: 0 }, target_minutes: 36, traits: ["Rim Protector", "Alpha Dog"], foul_tendency: 7, img_url: `https://www.statmuse.com/img/nba/players/${toSlug("Bill Russell")}.png`, era: "Pioneers Era (1940s-1960s)" },
    "kobe_bryant": { name: "Kobe Bryant", pos: "SG", tier: "GOAT", attributes: { inside_scoring: 95, mid_range: 98, three_point: 85, playmaking: 86, perimeter_defense: 94, interior_defense: 65, rebounding: 70, athleticism: 95, basketball_iq: 96 }, career_stats: { usg_pct: 31.8, fg_pct: 44.7 }, shot_tendencies: { inside: 35, mid: 45, three: 20 }, target_minutes: 37, traits: ["Clutch Performer", "Alpha Dog", "Unstoppable Scorer"], foul_tendency: 5, img_url: `https://www.statmuse.com/img/nba/players/${toSlug("Kobe Bryant")}.png`, era: "Hyper-Modern Era (2010s-2020s)" },
    "tim_duncan": { name: "Tim Duncan", pos: "PF", tier: "GOAT", attributes: { inside_scoring: 96, mid_range: 90, three_point: 30, playmaking: 78, perimeter_defense: 75, interior_defense: 98, rebounding: 95, athleticism: 85, basketball_iq: 98 }, career_stats: { usg_pct: 27.0, fg_pct: 50.6 }, shot_tendencies: { inside: 75, mid: 25, three: 0 }, target_minutes: 36, traits: ["Post Anchor", "Rim Protector", "Floor General"], foul_tendency: 5, img_url: `https://www.statmuse.com/img/nba/players/${toSlug("Tim Duncan")}.png`, era: "Modern Era (1990s-2000s)" },
    
    // Legend Tier
    "stephen_curry": { name: "Stephen Curry", pos: "PG", tier: "Legend", attributes: { inside_scoring: 88, mid_range: 92, three_point: 100, playmaking: 92, perimeter_defense: 80, interior_defense: 40, rebounding: 65, athleticism: 88, basketball_iq: 95 }, career_stats: { usg_pct: 29.0, fg_pct: 47.3 }, shot_tendencies: { inside: 25, mid: 25, three: 50 }, target_minutes: 35, traits: ["Heat Check", "Floor General", "Unstoppable Scorer"], foul_tendency: 3, img_url: `https://www.statmuse.com/img/nba/players/${toSlug("Stephen Curry")}.png`, era: "Hyper-Modern Era (2010s-2020s)" },
    "kevin_durant": { name: "Kevin Durant", pos: "SF", tier: "Legend", attributes: { inside_scoring: 94, mid_range: 99, three_point: 92, playmaking: 85, perimeter_defense: 85, interior_defense: 80, rebounding: 80, athleticism: 90, basketball_iq: 94 }, career_stats: { usg_pct: 30.3, fg_pct: 49.3 }, shot_tendencies: { inside: 30, mid: 40, three: 30 }, target_minutes: 37, traits: ["Unstoppable Scorer", "Heat Check", "Clutch Performer"], foul_tendency: 4, img_url: `https://www.statmuse.com/img/nba/players/${toSlug("Kevin Durant")}.png`, era: "Hyper-Modern Era (2010s-2020s)" },
    "hakeem_olajuwon": { name: "Hakeem Olajuwon", pos: "C", tier: "Legend", attributes: { inside_scoring: 97, mid_range: 85, three_point: 20, playmaking: 70, perimeter_defense: 75, interior_defense: 99, rebounding: 93, athleticism: 92, basketball_iq: 95 }, career_stats: { usg_pct: 28.9, fg_pct: 51.2 }, shot_tendencies: { inside: 75, mid: 25, three: 0 }, target_minutes: 36, traits: ["Unstoppable Scorer", "Rim Protector"], foul_tendency: 8, img_url: `https://www.statmuse.com/img/nba/players/${toSlug("Hakeem Olajuwon")}.png`, era: "Modern Era (1990s-2000s)" },
    "shaquille_oneal": { name: "Shaquille O'Neal", pos: "C", tier: "Legend", attributes: { inside_scoring: 100, mid_range: 25, three_point: 5, playmaking: 65, perimeter_defense: 30, interior_defense: 92, rebounding: 94, athleticism: 95, basketball_iq: 80 }, career_stats: { usg_pct: 29.5, fg_pct: 58.2 }, shot_tendencies: { inside: 99, mid: 1, three: 0 }, target_minutes: 35, traits: ["Post Anchor", "Rim Protector"], foul_tendency: 9, img_url: `https://www.statmuse.com/img/nba/players/${toSlug("Shaquille O'Neal")}.png`, era: "Modern Era (1990s-2000s)" },
    "oscar_robertson": { name: "Oscar Robertson", pos: "PG", tier: "Legend", attributes: { inside_scoring: 90, mid_range: 92, three_point: 50, playmaking: 98, perimeter_defense: 85, interior_defense: 60, rebounding: 82, athleticism: 85, basketball_iq: 96 }, career_stats: { usg_pct: 26.0, fg_pct: 48.5 }, shot_tendencies: { inside: 50, mid: 50, three: 0 }, target_minutes: 38, traits: ["Floor General", "Tireless Motor"], foul_tendency: 5, img_url: `https://www.statmuse.com/img/nba/players/${toSlug("Oscar Robertson")}.png`, era: "Pioneers Era (1940s-1960s)" },
    "dirk_nowitzki": { name: "Dirk Nowitzki", pos: "PF", tier: "Legend", attributes: { inside_scoring: 85, mid_range: 98, three_point: 88, playmaking: 75, perimeter_defense: 60, interior_defense: 70, rebounding: 85, athleticism: 78, basketball_iq: 95 }, career_stats: { usg_pct: 28.0, fg_pct: 47.1 }, shot_tendencies: { inside: 25, mid: 50, three: 25 }, target_minutes: 34, traits: ["Unstoppable Scorer", "Clutch Performer"], foul_tendency: 4, img_url: `https://www.statmuse.com/img/nba/players/${toSlug("Dirk Nowitzki")}.png`, era: "Hyper-Modern Era (2010s-2020s)" },
    "kevin_garnett": { name: "Kevin Garnett", pos: "PF", tier: "Legend", attributes: { inside_scoring: 90, mid_range: 94, three_point: 60, playmaking: 82, perimeter_defense: 95, interior_defense: 94, rebounding: 92, athleticism: 90, basketball_iq: 93 }, career_stats: { usg_pct: 26.3, fg_pct: 49.7 }, shot_tendencies: { inside: 40, mid: 55, three: 5 }, target_minutes: 36, traits: ["Alpha Dog", "Rim Protector", "Tireless Motor"], foul_tendency: 6, img_url: `https://www.statmuse.com/img/nba/players/${toSlug("Kevin Garnett")}.png`, era: "Modern Era (1990s-2000s)" },
    "karl_malone": { name: "Karl Malone", pos: "PF", tier: "Legend", attributes: { inside_scoring: 95, mid_range: 88, three_point: 40, playmaking: 70, perimeter_defense: 78, interior_defense: 75, rebounding: 90, athleticism: 94, basketball_iq: 85 }, career_stats: { usg_pct: 28.7, fg_pct: 51.6 }, shot_tendencies: { inside: 60, mid: 40, three: 0 }, target_minutes: 37, traits: ["Post Anchor", "Transition Threat"], foul_tendency: 8, img_url: `https://www.statmuse.com/img/nba/players/${toSlug("Karl Malone")}.png`, era: "Modern Era (1990s-2000s)" },
    "julius_erving": { name: "Julius Erving", pos: "SF", tier: "Legend", attributes: { inside_scoring: 97, mid_range: 80, three_point: 65, playmaking: 80, perimeter_defense: 85, interior_defense: 75, rebounding: 85, athleticism: 96, basketball_iq: 90 }, career_stats: { usg_pct: 28.8, fg_pct: 50.6 }, shot_tendencies: { inside: 70, mid: 25, three: 5 }, target_minutes: 36, traits: ["Transition Threat", "Unstoppable Scorer"], foul_tendency: 6, img_url: `https://www.statmuse.com/img/nba/players/${toSlug("Julius Erving")}.png`, era: "Showtime & Three-Point Era (1970s-1980s)" },
    "moses_malone": { name: "Moses Malone", pos: "C", tier: "Legend", attributes: { inside_scoring: 94, mid_range: 70, three_point: 20, playmaking: 60, perimeter_defense: 60, interior_defense: 88, rebounding: 98, athleticism: 85, basketball_iq: 88 }, career_stats: { usg_pct: 26.1, fg_pct: 49.1 }, shot_tendencies: { inside: 85, mid: 15, three: 0 }, target_minutes: 34, traits: ["Post Anchor", "Tireless Motor"], foul_tendency: 7, img_url: `https://www.statmuse.com/img/nba/players/${toSlug("Moses Malone")}.png`, era: "Showtime & Three-Point Era (1970s-1980s)" },
    "jerry_west": { name: "Jerry West", pos: "SG", tier: "Legend", attributes: { inside_scoring: 85, mid_range: 95, three_point: 80, playmaking: 90, perimeter_defense: 92, interior_defense: 60, rebounding: 70, athleticism: 88, basketball_iq: 94 }, career_stats: { usg_pct: 30.0, fg_pct: 47.4 }, shot_tendencies: { inside: 40, mid: 60, three: 0 }, target_minutes: 37, traits: ["Clutch Performer", "Unstoppable Scorer"], foul_tendency: 5, img_url: `https://www.statmuse.com/img/nba/players/${toSlug("Jerry West")}.png`, era: "Pioneers Era (1940s-1960s)" },
    "elgin_baylor": { name: "Elgin Baylor", pos: "SF", tier: "Legend", attributes: { inside_scoring: 96, mid_range: 90, three_point: 40, playmaking: 80, perimeter_defense: 78, interior_defense: 65, rebounding: 92, athleticism: 93, basketball_iq: 90 }, career_stats: { usg_pct: 29.0, fg_pct: 43.1 }, shot_tendencies: { inside: 60, mid: 40, three: 0 }, target_minutes: 36, traits: ["Unstoppable Scorer", "Tireless Motor"], foul_tendency: 6, img_url: `https://www.statmuse.com/img/nba/players/${toSlug("Elgin Baylor")}.png`, era: "Pioneers Era (1940s-1960s)" },
    "dwyane_wade": { name: "Dwyane Wade", pos: "SG", tier: "Legend", attributes: { inside_scoring: 96, mid_range: 84, three_point: 75, playmaking: 88, perimeter_defense: 90, interior_defense: 75, rebounding: 68, athleticism: 94, basketball_iq: 92 }, career_stats: { usg_pct: 32.0, fg_pct: 48.0 }, shot_tendencies: { inside: 55, mid: 35, three: 10 }, target_minutes: 35, traits: ["Clutch Performer", "Transition Threat", "Ankle Breaker"], foul_tendency: 5, img_url: `https://www.statmuse.com/img/nba/players/${toSlug("Dwyane Wade")}.png`, era: "Hyper-Modern Era (2010s-2020s)" },
    "giannis_antetokounmpo": { name: "Giannis Antetokounmpo", pos: "PF", tier: "Legend", attributes: { inside_scoring: 99, mid_range: 72, three_point: 70, playmaking: 85, perimeter_defense: 92, interior_defense: 90, rebounding: 93, athleticism: 100, basketball_iq: 90 }, career_stats: { usg_pct: 32.5, fg_pct: 53.5 }, shot_tendencies: { inside: 75, mid: 15, three: 10 }, target_minutes: 34, traits: ["Transition Threat", "Unstoppable Scorer", "Rim Protector"], foul_tendency: 7, img_url: `https://www.statmuse.com/img/nba/players/${toSlug("Giannis Antetokounmpo")}.png`, era: "Hyper-Modern Era (2010s-2020s)" },
    "scottie_pippen": { name: "Scottie Pippen", pos: "SF", tier: "Legend", attributes: { inside_scoring: 85, mid_range: 82, three_point: 75, playmaking: 88, perimeter_defense: 100, interior_defense: 80, rebounding: 80, athleticism: 92, basketball_iq: 93 }, career_stats: { usg_pct: 21.0, fg_pct: 47.3 }, shot_tendencies: { inside: 45, mid: 35, three: 20 }, target_minutes: 35, traits: ["Lockdown Defender", "Transition Threat"], foul_tendency: 4, img_url: `https://www.statmuse.com/img/nba/players/${toSlug("Scottie Pippen")}.png`, era: "Modern Era (1990s-2000s)" },
    "charles_barkley": { name: "Charles Barkley", pos: "PF", tier: "Legend", attributes: { inside_scoring: 92, mid_range: 80, three_point: 70, playmaking: 75, perimeter_defense: 70, interior_defense: 65, rebounding: 95, athleticism: 90, basketball_iq: 87 }, career_stats: { usg_pct: 26.6, fg_pct: 54.1 }, shot_tendencies: { inside: 65, mid: 25, three: 10 }, target_minutes: 35, traits: ["Tireless Motor", "Post Anchor"], foul_tendency: 8, img_url: `https://www.statmuse.com/img/nba/players/${toSlug("Charles Barkley")}.png`, era: "Modern Era (1990s-2000s)" },
    "john_stockton": { name: "John Stockton", pos: "PG", tier: "Legend", attributes: { inside_scoring: 75, mid_range: 85, three_point: 82, playmaking: 99, perimeter_defense: 94, interior_defense: 40, rebounding: 50, athleticism: 80, basketball_iq: 97 }, career_stats: { usg_pct: 18.0, fg_pct: 51.5 }, shot_tendencies: { inside: 40, mid: 40, three: 20 }, target_minutes: 34, traits: ["Floor General", "Lockdown Defender"], foul_tendency: 4, img_url: `https://www.statmuse.com/img/nba/players/${toSlug("John Stockton")}.png`, era: "Modern Era (1990s-2000s)" },
    "allen_iverson": { name: "Allen Iverson", pos: "SG", tier: "Legend", attributes: { inside_scoring: 94, mid_range: 88, three_point: 78, playmaking: 88, perimeter_defense: 88, interior_defense: 45, rebounding: 60, athleticism: 98, basketball_iq: 85 }, career_stats: { usg_pct: 31.8, fg_pct: 42.5 }, shot_tendencies: { inside: 50, mid: 35, three: 15 }, target_minutes: 38, traits: ["Ankle Breaker", "Unstoppable Scorer", "Tireless Motor"], foul_tendency: 4, img_url: `https://www.statmuse.com/img/nba/players/${toSlug("Allen Iverson")}.png`, era: "Modern Era (1990s-2000s)" },
    "isiah_thomas": { name: "Isiah Thomas", pos: "PG", tier: "Legend", attributes: { inside_scoring: 88, mid_range: 86, three_point: 70, playmaking: 95, perimeter_defense: 88, interior_defense: 45, rebounding: 60, athleticism: 91, basketball_iq: 92 }, career_stats: { usg_pct: 26.2, fg_pct: 45.2 }, shot_tendencies: { inside: 50, mid: 40, three: 10 }, target_minutes: 36, traits: ["Ankle Breaker", "Floor General"], foul_tendency: 6, img_url: `https://www.statmuse.com/img/nba/players/${toSlug("Isiah Thomas")}.png`, era: "Showtime & Three-Point Era (1970s-1980s)" },
    "kawhi_leonard": { name: "Kawhi Leonard", pos: "SF", tier: "Legend", attributes: { inside_scoring: 90, mid_range: 95, three_point: 85, playmaking: 80, perimeter_defense: 100, interior_defense: 75, rebounding: 80, athleticism: 92, basketball_iq: 94 }, career_stats: { usg_pct: 27.0, fg_pct: 49.3 }, shot_tendencies: { inside: 30, mid: 50, three: 20 }, target_minutes: 34, traits: ["Lockdown Defender", "Clutch Performer", "Alpha Dog"], foul_tendency: 3, img_url: `https://www.statmuse.com/img/nba/players/${toSlug("Kawhi Leonard")}.png`, era: "Hyper-Modern Era (2010s-2020s)" },
    "patrick_ewing": { name: "Patrick Ewing", pos: "C", tier: "Legend", attributes: { inside_scoring: 90, mid_range: 92, three_point: 20, playmaking: 60, perimeter_defense: 50, interior_defense: 94, rebounding: 91, athleticism: 86, basketball_iq: 84 }, career_stats: { usg_pct: 29.0, fg_pct: 50.4 }, shot_tendencies: { inside: 50, mid: 50, three: 0 }, target_minutes: 35, traits: ["Rim Protector", "Unstoppable Scorer"], foul_tendency: 7, img_url: `https://www.statmuse.com/img/nba/players/${toSlug("Patrick Ewing")}.png`, era: "Modern Era (1990s-2000s)" },
    "david_robinson": { name: "David Robinson", pos: "C", tier: "Legend", attributes: { inside_scoring: 93, mid_range: 84, three_point: 50, playmaking: 70, perimeter_defense: 70, interior_defense: 95, rebounding: 92, athleticism: 95, basketball_iq: 91 }, career_stats: { usg_pct: 28.5, fg_pct: 51.8 }, shot_tendencies: { inside: 65, mid: 30, three: 5 }, target_minutes: 34, traits: ["Rim Protector", "Transition Threat"], foul_tendency: 6, img_url: `https://www.statmuse.com/img/nba/players/${toSlug("David Robinson")}.png`, era: "Modern Era (1990s-2000s)" },
    "clyde_drexler": { name: "Clyde Drexler", pos: "SG", tier: "Legend", attributes: { inside_scoring: 90, mid_range: 80, three_point: 78, playmaking: 85, perimeter_defense: 84, interior_defense: 60, rebounding: 78, athleticism: 94, basketball_iq: 88 }, career_stats: { usg_pct: 26.1, fg_pct: 47.2 }, shot_tendencies: { inside: 50, mid: 30, three: 20 }, target_minutes: 34, traits: ["Transition Threat", "Ankle Breaker"], foul_tendency: 5, img_url: `https://www.statmuse.com/img/nba/players/${toSlug("Clyde Drexler")}.png`, era: "Modern Era (1990s-2000s)" },
    "george_gervin": { name: "George Gervin", pos: "SG", tier: "Legend", attributes: { inside_scoring: 94, mid_range: 96, three_point: 60, playmaking: 70, perimeter_defense: 70, interior_defense: 50, rebounding: 65, athleticism: 87, basketball_iq: 85 }, career_stats: { usg_pct: 32.8, fg_pct: 51.1 }, shot_tendencies: { inside: 50, mid: 50, three: 0 }, target_minutes: 33, traits: ["Unstoppable Scorer", "Heat Check"], foul_tendency: 7, img_url: `https://www.statmuse.com/img/nba/players/${toSlug("George Gervin")}.png`, era: "Showtime & Three-Point Era (1970s-1980s)" },
    "john_havlicek": { name: "John Havlicek", pos: "SF", tier: "Legend", attributes: { inside_scoring: 86, mid_range: 88, three_point: 50, playmaking: 85, perimeter_defense: 90, interior_defense: 65, rebounding: 78, athleticism: 88, basketball_iq: 93 }, career_stats: { usg_pct: 25.0, fg_pct: 43.9 }, shot_tendencies: { inside: 50, mid: 50, three: 0 }, target_minutes: 36, traits: ["Tireless Motor", "Clutch Performer"], foul_tendency: 4, img_url: `https://www.statmuse.com/img/nba/players/${toSlug("John Havlicek")}.png`, era: "Pioneers Era (1940s-1960s)" },
    "rick_barry": { name: "Rick Barry", pos: "SF", tier: "Legend", attributes: { inside_scoring: 84, mid_range: 90, three_point: 80, playmaking: 86, perimeter_defense: 82, interior_defense: 60, rebounding: 75, athleticism: 84, basketball_iq: 90 }, career_stats: { usg_pct: 27.5, fg_pct: 44.9 }, shot_tendencies: { inside: 40, mid: 40, three: 20 }, target_minutes: 35, traits: ["Unstoppable Scorer", "Floor General"], foul_tendency: 6, img_url: `https://www.statmuse.com/img/nba/players/${toSlug("Rick Barry")}.png`, era: "Showtime & Three-Point Era (1970s-1980s)" },
    "bob_pettit": { name: "Bob Pettit", pos: "PF", tier: "Legend", attributes: { inside_scoring: 92, mid_range: 85, three_point: 30, playmaking: 70, perimeter_defense: 70, interior_defense: 75, rebounding: 96, athleticism: 85, basketball_iq: 88 }, career_stats: { usg_pct: 28.0, fg_pct: 43.6 }, shot_tendencies: { inside: 60, mid: 40, three: 0 }, target_minutes: 36, traits: ["Tireless Motor", "Post Anchor"], foul_tendency: 7, img_url: `https://www.statmuse.com/img/nba/players/${toSlug("Bob Pettit")}.png`, era: "Pioneers Era (1940s-1960s)" },
    "dominique_wilkins": { name: "Dominique Wilkins", pos: "SF", tier: "Legend", attributes: { inside_scoring: 95, mid_range: 88, three_point: 72, playmaking: 70, perimeter_defense: 70, interior_defense: 60, rebounding: 78, athleticism: 98, basketball_iq: 82 }, career_stats: { usg_pct: 30.3, fg_pct: 46.1 }, shot_tendencies: { inside: 60, mid: 30, three: 10 }, target_minutes: 35, traits: ["Transition Threat", "Unstoppable Scorer"], foul_tendency: 5, img_url: `https://www.statmuse.com/img/nba/players/${toSlug("Dominique Wilkins")}.png`, era: "Showtime & Three-Point Era (1970s-1980s)" },
    
    // All-Star Tier
    "chris_paul": { name: "Chris Paul", pos: "PG", tier: "All-Star", attributes: { inside_scoring: 80, mid_range: 90, three_point: 84, playmaking: 98, perimeter_defense: 92, interior_defense: 40, rebounding: 60, athleticism: 86, basketball_iq: 98 }, career_stats: { usg_pct: 24.0, fg_pct: 47.2 }, shot_tendencies: { inside: 30, mid: 50, three: 20 }, target_minutes: 33, traits: ["Floor General", "Clutch Performer"], foul_tendency: 4, img_url: `https://www.statmuse.com/img/nba/players/${toSlug("Chris Paul")}.png`, era: "Hyper-Modern Era (2010s-2020s)" },
    "james_harden": { name: "James Harden", pos: "SG", tier: "All-Star", attributes: { inside_scoring: 92, mid_range: 80, three_point: 90, playmaking: 94, perimeter_defense: 78, interior_defense: 60, rebounding: 75, athleticism: 88, basketball_iq: 91 }, career_stats: { usg_pct: 30.0, fg_pct: 44.2 }, shot_tendencies: { inside: 40, mid: 15, three: 45 }, target_minutes: 36, traits: ["Unstoppable Scorer", "Ankle Breaker", "Floor General"], foul_tendency: 5, img_url: `https://www.statmuse.com/img/nba/players/${toSlug("James Harden")}.png`, era: "Hyper-Modern Era (2010s-2020s)" },
    "russell_westbrook": { name: "Russell Westbrook", pos: "PG", tier: "All-Star", attributes: { inside_scoring: 92, mid_range: 78, three_point: 75, playmaking: 93, perimeter_defense: 84, interior_defense: 55, rebounding: 85, athleticism: 99, basketball_iq: 86 }, career_stats: { usg_pct: 32.5, fg_pct: 43.7 }, shot_tendencies: { inside: 55, mid: 25, three: 20 }, target_minutes: 35, traits: ["Transition Threat", "Tireless Motor", "Ankle Breaker"], foul_tendency: 6, img_url: `https://www.statmuse.com/img/nba/players/${toSlug("Russell Westbrook")}.png`, era: "Hyper-Modern Era (2010s-2020s)" },
    "gary_payton": { name: "Gary Payton", pos: "PG", tier: "All-Star", attributes: { inside_scoring: 82, mid_range: 86, three_point: 75, playmaking: 90, perimeter_defense: 99, interior_defense: 50, rebounding: 65, athleticism: 88, basketball_iq: 92 }, career_stats: { usg_pct: 25.0, fg_pct: 46.6 }, shot_tendencies: { inside: 45, mid: 40, three: 15 }, target_minutes: 36, traits: ["Lockdown Defender", "Floor General"], foul_tendency: 5, img_url: `https://www.statmuse.com/img/nba/players/${toSlug("Gary Payton")}.png`, era: "Modern Era (1990s-2000s)" },
    "jason_kidd": { name: "Jason Kidd", pos: "PG", tier: "All-Star", attributes: { inside_scoring: 78, mid_range: 75, three_point: 80, playmaking: 97, perimeter_defense: 93, interior_defense: 50, rebounding: 78, athleticism: 85, basketball_iq: 96 }, career_stats: { usg_pct: 19.0, fg_pct: 40.0 }, shot_tendencies: { inside: 40, mid: 25, three: 35 }, target_minutes: 36, traits: ["Floor General", "Lockdown Defender", "Transition Threat"], foul_tendency: 4, img_url: `https://www.statmuse.com/img/nba/players/${toSlug("Jason Kidd")}.png`, era: "Modern Era (1990s-2000s)" },
    "steve_nash": { name: "Steve Nash", pos: "PG", tier: "All-Star", attributes: { inside_scoring: 75, mid_range: 88, three_point: 91, playmaking: 98, perimeter_defense: 65, interior_defense: 30, rebounding: 50, athleticism: 84, basketball_iq: 97 }, career_stats: { usg_pct: 20.0, fg_pct: 49.0 }, shot_tendencies: { inside: 25, mid: 40, three: 35 }, target_minutes: 32, traits: ["Floor General", "Heat Check"], foul_tendency: 3, img_url: `https://www.statmuse.com/img/nba/players/${toSlug("Steve Nash")}.png`, era: "Modern Era (1990s-2000s)" },
    "ray_allen": { name: "Ray Allen", pos: "SG", tier: "All-Star", attributes: { inside_scoring: 82, mid_range: 90, three_point: 98, playmaking: 80, perimeter_defense: 80, interior_defense: 40, rebounding: 60, athleticism: 86, basketball_iq: 90 }, career_stats: { usg_pct: 24.0, fg_pct: 45.2 }, shot_tendencies: { inside: 20, mid: 40, three: 40 }, target_minutes: 34, traits: ["Heat Check", "Clutch Performer", "Tireless Motor"], foul_tendency: 4, img_url: `https://www.statmuse.com/img/nba/players/${toSlug("Ray Allen")}.png`, era: "Modern Era (1990s-2000s)" },
    "reggie_miller": { name: "Reggie Miller", pos: "SG", tier: "All-Star", attributes: { inside_scoring: 75, mid_range: 88, three_point: 97, playmaking: 75, perimeter_defense: 78, interior_defense: 35, rebounding: 50, athleticism: 84, basketball_iq: 91 }, career_stats: { usg_pct: 22.0, fg_pct: 47.1 }, shot_tendencies: { inside: 15, mid: 40, three: 45 }, target_minutes: 34, traits: ["Clutch Performer", "Heat Check", "Alpha Dog"], foul_tendency: 4, img_url: `https://www.statmuse.com/img/nba/players/${toSlug("Reggie Miller")}.png`, era: "Modern Era (1990s-2000s)" },
    "paul_pierce": { name: "Paul Pierce", pos: "SF", tier: "All-Star", attributes: { inside_scoring: 88, mid_range: 90, three_point: 85, playmaking: 82, perimeter_defense: 80, interior_defense: 60, rebounding: 75, athleticism: 82, basketball_iq: 92 }, career_stats: { usg_pct: 26.5, fg_pct: 44.5 }, shot_tendencies: { inside: 35, mid: 40, three: 25 }, target_minutes: 34, traits: ["Clutch Performer", "Unstoppable Scorer"], foul_tendency: 5, img_url: `https://www.statmuse.com/img/nba/players/${toSlug("Paul Pierce")}.png`, era: "Modern Era (1990s-2000s)" },
    "carmelo_anthony": { name: "Carmelo Anthony", pos: "SF", tier: "All-Star", attributes: { inside_scoring: 89, mid_range: 95, three_point: 84, playmaking: 75, perimeter_defense: 68, interior_defense: 62, rebounding: 78, athleticism: 84, basketball_iq: 85 }, career_stats: { usg_pct: 29.0, fg_pct: 44.7 }, shot_tendencies: { inside: 30, mid: 45, three: 25 }, target_minutes: 35, traits: ["Unstoppable Scorer", "Clutch Performer"], foul_tendency: 5, img_url: `https://www.statmuse.com/img/nba/players/${toSlug("Carmelo Anthony")}.png`, era: "Hyper-Modern Era (2010s-2020s)" },
    "anthony_davis": { name: "Anthony Davis", pos: "PF", tier: "All-Star", attributes: { inside_scoring: 94, mid_range: 86, three_point: 78, playmaking: 72, perimeter_defense: 88, interior_defense: 95, rebounding: 91, athleticism: 91, basketball_iq: 88 }, career_stats: { usg_pct: 27.5, fg_pct: 51.5 }, shot_tendencies: { inside: 55, mid: 30, three: 15 }, target_minutes: 35, traits: ["Rim Protector", "Unstoppable Scorer", "Transition Threat"], foul_tendency: 6, img_url: `https://www.statmuse.com/img/nba/players/${toSlug("Anthony Davis")}.png`, era: "Hyper-Modern Era (2010s-2020s)" },
    "damian_lillard": { name: "Damian Lillard", pos: "PG", tier: "All-Star", attributes: { inside_scoring: 86, mid_range: 88, three_point: 94, playmaking: 90, perimeter_defense: 75, interior_defense: 40, rebounding: 60, athleticism: 89, basketball_iq: 92 }, career_stats: { usg_pct: 28.5, fg_pct: 43.9 }, shot_tendencies: { inside: 30, mid: 25, three: 45 }, target_minutes: 36, traits: ["Clutch Performer", "Heat Check", "Alpha Dog"], foul_tendency: 3, img_url: `https://www.statmuse.com/img/nba/players/${toSlug("Damian Lillard")}.png`, era: "Hyper-Modern Era (2010s-2020s)" },
    "dennis_rodman": { name: "Dennis Rodman", pos: "PF", tier: "All-Star", attributes: { inside_scoring: 60, mid_range: 40, three_point: 20, playmaking: 60, perimeter_defense: 92, interior_defense: 90, rebounding: 100, athleticism: 88, basketball_iq: 85 }, career_stats: { usg_pct: 8.0, fg_pct: 52.1 }, shot_tendencies: { inside: 90, mid: 10, three: 0 }, target_minutes: 30, traits: ["Lockdown Defender", "Tireless Motor", "Post Anchor"], foul_tendency: 8, img_url: `https://www.statmuse.com/img/nba/players/${toSlug("Dennis Rodman")}.png`, era: "Modern Era (1990s-2000s)" },
    "walt_frazier": { name: "Walt Frazier", pos: "PG", tier: "All-Star", attributes: { inside_scoring: 80, mid_range: 88, three_point: 40, playmaking: 88, perimeter_defense: 97, interior_defense: 50, rebounding: 70, athleticism: 86, basketball_iq: 91 }, career_stats: { usg_pct: 24.0, fg_pct: 49.0 }, shot_tendencies: { inside: 40, mid: 60, three: 0 }, target_minutes: 34, traits: ["Lockdown Defender", "Floor General"], foul_tendency: 4, img_url: `https://www.statmuse.com/img/nba/players/${toSlug("Walt Frazier")}.png`, era: "Showtime & Three-Point Era (1970s-1980s)" },
    "kevin_mchale": { name: "Kevin McHale", pos: "PF", tier: "All-Star", attributes: { inside_scoring: 96, mid_range: 75, three_point: 30, playmaking: 65, perimeter_defense: 60, interior_defense: 90, rebounding: 85, athleticism: 80, basketball_iq: 89 }, career_stats: { usg_pct: 24.1, fg_pct: 55.4 }, shot_tendencies: { inside: 80, mid: 20, three: 0 }, target_minutes: 31, traits: ["Post Anchor", "Unstoppable Scorer"], foul_tendency: 7, img_url: `https://www.statmuse.com/img/nba/players/${toSlug("Kevin McHale")}.png`, era: "Showtime & Three-Point Era (1970s-1980s)" },
    "elvin_hayes": { name: "Elvin Hayes", pos: "PF", tier: "All-Star", attributes: { inside_scoring: 90, mid_range: 88, three_point: 20, playmaking: 60, perimeter_defense: 60, interior_defense: 85, rebounding: 94, athleticism: 84, basketball_iq: 82 }, career_stats: { usg_pct: 27.2, fg_pct: 45.2 }, shot_tendencies: { inside: 50, mid: 50, three: 0 }, target_minutes: 34, traits: ["Unstoppable Scorer", "Rim Protector"], foul_tendency: 7, img_url: `https://www.statmuse.com/img/nba/players/${toSlug("Elvin Hayes")}.png`, era: "Showtime & Three-Point Era (1970s-1980s)" },
    "robert_parish": { name: "Robert Parish", pos: "C", tier: "All-Star", attributes: { inside_scoring: 88, mid_range: 86, three_point: 10, playmaking: 60, perimeter_defense: 50, interior_defense: 89, rebounding: 88, athleticism: 78, basketball_iq: 85 }, career_stats: { usg_pct: 19.8, fg_pct: 53.7 }, shot_tendencies: { inside: 60, mid: 40, three: 0 }, target_minutes: 28, traits: ["Rim Protector", "Post Anchor"], foul_tendency: 6, img_url: `https://www.statmuse.com/img/nba/players/${toSlug("Robert Parish")}.png`, era: "Modern Era (1990s-2000s)" },
    "james_worthy": { name: "James Worthy", pos: "SF", tier: "All-Star", attributes: { inside_scoring: 92, mid_range: 85, three_point: 50, playmaking: 75, perimeter_defense: 75, interior_defense: 60, rebounding: 70, athleticism: 90, basketball_iq: 86 }, career_stats: { usg_pct: 22.5, fg_pct: 52.1 }, shot_tendencies: { inside: 60, mid: 35, three: 5 }, target_minutes: 32, traits: ["Transition Threat", "Clutch Performer"], foul_tendency: 5, img_url: `https://www.statmuse.com/img/nba/players/${toSlug("James Worthy")}.png`, era: "Showtime & Three-Point Era (1970s-1980s)" },
    "bob_cousy": { name: "Bob Cousy", pos: "PG", tier: "All-Star", attributes: { inside_scoring: 78, mid_range: 80, three_point: 30, playmaking: 97, perimeter_defense: 75, interior_defense: 40, rebounding: 60, athleticism: 82, basketball_iq: 94 }, career_stats: { usg_pct: 26.0, fg_pct: 37.5 }, shot_tendencies: { inside: 50, mid: 50, three: 0 }, target_minutes: 32, traits: ["Floor General", "Ankle Breaker"], foul_tendency: 5, img_url: `https://www.statmuse.com/img/nba/players/${toSlug("Bob Cousy")}.png`, era: "Pioneers Era (1940s-1960s)" },
    "nate_archibald": { name: "Nate Archibald", pos: "PG", tier: "All-Star", attributes: { inside_scoring: 88, mid_range: 82, three_point: 50, playmaking: 94, perimeter_defense: 80, interior_defense: 40, rebounding: 50, athleticism: 90, basketball_iq: 88 }, career_stats: { usg_pct: 25.0, fg_pct: 46.7 }, shot_tendencies: { inside: 60, mid: 35, three: 5 }, target_minutes: 33, traits: ["Floor General", "Ankle Breaker"], foul_tendency: 4, img_url: `https://www.statmuse.com/img/nba/players/${toSlug("Nate Archibald")}.png`, era: "Showtime & Three-Point Era (1970s-1980s)" },
    "bill_walton": { name: "Bill Walton", pos: "C", tier: "All-Star", attributes: { inside_scoring: 85, mid_range: 75, three_point: 20, playmaking: 88, perimeter_defense: 65, interior_defense: 92, rebounding: 93, athleticism: 82, basketball_iq: 95 }, career_stats: { usg_pct: 20.0, fg_pct: 52.1 }, shot_tendencies: { inside: 70, mid: 30, three: 0 }, target_minutes: 30, traits: ["Floor General", "Rim Protector"], foul_tendency: 7, img_url: `https://www.statmuse.com/img/nba/players/${toSlug("Bill Walton")}.png`, era: "Showtime & Three-Point Era (1970s-1980s)" },
    "pete_maravich": { name: "Pete Maravich", pos: "SG", tier: "All-Star", attributes: { inside_scoring: 85, mid_range: 88, three_point: 75, playmaking: 92, perimeter_defense: 70, interior_defense: 40, rebounding: 60, athleticism: 85, basketball_iq: 89 }, career_stats: { usg_pct: 30.5, fg_pct: 44.1 }, shot_tendencies: { inside: 40, mid: 40, three: 20 }, target_minutes: 34, traits: ["Ankle Breaker", "Heat Check"], foul_tendency: 5, img_url: `https://www.statmuse.com/img/nba/players/${toSlug("Pete Maravich")}.png`, era: "Showtime & Three-Point Era (1970s-1980s)" },
    "george_mikan": { name: "George Mikan", pos: "C", tier: "All-Star", attributes: { inside_scoring: 95, mid_range: 70, three_point: 5, playmaking: 65, perimeter_defense: 40, interior_defense: 88, rebounding: 90, athleticism: 70, basketball_iq: 85 }, career_stats: { usg_pct: 30.0, fg_pct: 40.4 }, shot_tendencies: { inside: 90, mid: 10, three: 0 }, target_minutes: 34, traits: ["Post Anchor", "Rim Protector"], foul_tendency: 9, img_url: `https://www.statmuse.com/img/nba/players/${toSlug("George Mikan")}.png`, era: "Pioneers Era (1940s-1960s)" }
};
